fix: random fixes

diff --git a/resources/case_studies/AIJ_A/bin/Allrun_case b/resources/case_studies/AIJ_A/bin/Allrun_case
--- a/resources/case_studies/AIJ_A/bin/Allrun_case
+++ b/resources/case_studies/AIJ_A/bin/Allrun_case
@@ -14,9 +14,9 @@ smoothing=false  # Set to True if you want to smooth the mesh (requires cfmesh)
 refinement=false # Set to True if you want to refine the mesh
 
 # Local folders
-local_resources="resources"                       # Folder with resources
-local_dicts="system"                              # Folder for local dictionaries
-local_properties="constant"                       # Folder for local properties
+local_resources="resources" # Folder with resources
+local_dicts="system"        # Folder for local dictionaries
+local_props="constant"      # Folder for local properties
 
 #------------------------------------------------------------------------------
 # Source utility functions
@@ -29,7 +29,7 @@ local_properties="constant"                       # Folder for local properties
 #------------------------------------------------------------------------------
 # Check if local directories are empty
 
-for folder in "${local_dicts}" "${local_properties}"; do
+for folder in "${local_dicts}" "${local_props}"; do
     check_if_empty "$folder"
 done
 
@@ -40,7 +40,7 @@ resources=$(check_resources -r "${local_resources}")
 read -r dicts_resources \
         data_resources \
         geometry_resources \
-        properties_resources \
+        props_resources \
         functions_resources <<< ${resources}
 
 declare -A files_to_copy=(
@@ -51,15 +51,12 @@ declare -A files_to_copy=(
     ["${dicts_resources}/fvSchemes"]="${local_dicts}/fvSchemes"
     ["${dicts_resources}/controlDict"]="${local_dicts}/controlDict"
     ["${dicts_resources}/userDict"]="${local_dicts}/userDict"
-    ["${properties_resources}/transportProperties"]
-        ="${local_properties}/transportProperties"
-    ["${properties_resources}/turbulenceProperties"]
-        ="${local_properties}/turbulenceProperties"
+    ["${props_resources}/transportProperties"]="${local_props}/transportProperties"
+    ["${props_resources}/turbulenceProperties"]="${local_props}/turbulenceProperties"
 )
 
 if [ "${refinement}" = true ]; then
-    files_to_copy["${dicts_resources}/dynamicMeshDict"]
-        ="${local_properties}/dynamicMeshDict"
+    files_to_copy["${dicts_resources}/dynamicMeshDict"]="${local_props}/dynamicMeshDict"
 fi
 
 for source in "${!files_to_copy[@]}"; do
@@ -72,8 +69,8 @@ cp -r "${functions_resources}" "${local_dicts}/." || {
     exit 1
 }
 
-cp -r "${data_resources}/boundaryData" "${local_properties}/." || {
-    echo "Error copying boundary data to ${local_properties} folder" >&2
+cp -r "${data_resources}/boundaryData" "${local_props}/." || {
+    echo "Error copying boundary data to ${local_props} folder" >&2
     exit 1
 }
 
@@ -99,7 +96,7 @@ if [ "${refinement}" = true ]; then
     )
     set_lib "mydynamicFvMesh" "${local_dicts}/controlDict"
     set_lib "myincompressibleTurbulenceModels" "${local_dicts}/controlDict"
-    set_turbuence_model "mykOmegaSSTSAS" "${local_properties}/turbulenceProperties"
+    set_turbulence_model "mykOmegaSSTSAS" "${local_props}/turbulenceProperties"
 fi
 
 set_fos "${local_dicts}/function_objects"
@@ -111,7 +108,7 @@ set_parallel $n_proc "${local_dicts}/decomposeParDict"
 #------------------------------------------------------------------------------
 # Create the computation domain if has not been created yet
 
-if [ ! -d "${local_properties}/polyMesh" ]; then
+if [ ! -d "${local_props}/polyMesh" ]; then
     echo "Creating the mesh..."
     ./Allrun_pre "${smoothing}"
 else
