fix(AIJ_A): minor changes in case files and executable scripts

diff --git a/resources/case_studies/AIJ_A/bin/Allrun_case b/resources/case_studies/AIJ_A/bin/Allrun_case
--- a/resources/case_studies/AIJ_A/bin/Allrun_case
+++ b/resources/case_studies/AIJ_A/bin/Allrun_case
@@ -5,30 +5,39 @@ cd "${0%/*}" || exit
 #------------------------------------------------------------------------------
 
 # User parameters
-n_proc=16        # Set number of processors for parallel computing
-scale=0.25      # Set cells number scaling parameter
-delta_t=0.05     # Set acquisition time of post-processing
-start_time=1.3   # Set time to start averaging the solution (end of transient startup)
-end_time=2.0     # Set time to end the simulation
-smoothing=True  # Set to True if you want to smooth the mesh (requires cfmesh)
+n_proc=16      # Set number of processors for parallel computing
+scale=0.25     # Set cells number scaling parameter
+delta_t=0.05   # Set acquisition time of post-processing
+start_time=1.8 # Set time to start averaging the solution (end of transient startup)
+end_time=3.5   # Set time to end the simulation
+smoothing=True # Set to True if you want to smooth the mesh (requires cfmesh)
 
-local_resources="resources"     # Directory with resources
-local_dicts="system"            # Directory for local dictionaries
-local_properties="constant"     # Directory for local properties
-local_functions="${local_dicts}/function_objects" # Directory for local function objects
+# Local folders
+local_resources="resources"                       # Folder with resources
+local_dicts="system"                              # Folder for local dictionaries
+local_properties="constant"                       # Folder for local properties
 
 #------------------------------------------------------------------------------
 # Source utility functions
+
 . ./Util_functions || {
     echo "Util_functions not found in current folder" >&2
     exit 1
 }
 
 #------------------------------------------------------------------------------
+# Check if local directories are empty
+
+for folder in "${local_dicts}" "${local_properties}"; do
+    check_if_empty "$folder"
+done
+
+#------------------------------------------------------------------------------
 # Copy source files and folders
 
 resources=$(check_resources -r "${local_resources}")
 read -r dicts_resources \
+        data_resources \
         geometry_reosurces \
         properties_resources \
         functions_resources <<< ${resources}
@@ -50,8 +59,13 @@ for source in "${!files_to_copy[@]}"; do
     copy_file_if_exists "$source" "$target"
 done
 
-cp -r ${functions_resources} ${local_functions} || {
-    echo "Error copying function objects to ${local_functions}" >&2
+cp -r ${functions_resources} "${local_dicts}/." || {
+    echo "Error copying function objects to ${local_dicts} folder" >&2
+    exit 1
+}
+
+cp -r "${data_resources}/boundaryData" "${local_properties}/." || {
+    echo "Error copying boundary data to ${local_properties} folder" >&2
     exit 1
 }
 
@@ -59,16 +73,16 @@ cp -r ${functions_resources} ${local_functions} || {
 # Make changes in files
 
 protected_fos=(
-    "${local_functions}/FO_yPlus_4"
-    "${local_functions}/FO_sampleyPlus_5"
-    "${local_functions}/FO_residuals_6"
-    "${local_functions}/FO_fieldAverage_9"
-    "${local_functions}/FO_setMaxCo_16"
-    "${local_functions}/FO_setRelaxationFactors_17"
-    "${local_functions}/FO_setOuterCorrectors_18"
+    "FO_yPlus_4"
+    "FO_sampleyPlus_5"
+    "FO_residuals_6"
+    "FO_fieldAverage_9"
+    "FO_setMaxCo_16"
+    "FO_setRelaxationFactors_17"
+    "FO_setOuterCorrectors_18"
 )
 
-set_fos "${local_functions}"
+set_fos "${local_dicts}/function_objects"
 set_acquisition_time $delta_t $start_time $end_time "${protected_fos[@]}"
 set_scaling $scale "${local_dicts}/userDict"
 set_parallel $n_proc "${local_dicts}/decomposeParDict"
