feat(bin): add support to handle OpenFOAM foundation files and theoretical boundary conditions

diff --git a/resources/bin/Prepare b/resources/bin/Prepare
--- a/resources/bin/Prepare
+++ b/resources/bin/Prepare
@@ -12,7 +12,7 @@
 #
 # • Ready-to-run test cases are located in the resources/case_studies directory
 #   and their structure must be as follows:
-#   <case_name>
+#   <case_name>/<resources-folder>
 #   ├── README.md
 #   ├── bin                         --> <caseFolder>/
 #   │   ├── Allrun_case
@@ -55,7 +55,10 @@ RESOURCES_DIR="${ROOT_DIR}/resources"
 CASE_STUDIES_DIR="${RESOURCES_DIR}/case_studies"
 BIN_DIR="${RESOURCES_DIR}/bin"
 SLURM_DIR="${RESOURCES_DIR}/slurm"
+
+CASE_RESOURCES="resources"
 ALLRUN_ANALYSIS_SCRIPT="Allrun_analysis"
+ZERO_FOLDER="0.orig"
 
 #--- Usage Function ---#
 usage() {
@@ -79,6 +82,10 @@ usage() {
     Options:
         -a, --analysis      Enable analysis mode (default: off)
         -s, --slurm         Use slurm scripts (default: off)
+        -t, --theoretical   Use theoretical boundary conditions instead of
+                            experimental (default: experimental)
+        -r, --resources     Change case resources directory (default:
+                            <case_name>/resources)
         -h, --help          Show this help message and exit
 EOF
 }
@@ -102,6 +109,18 @@ parse_args() {
                     ALLRUN_ANALYSIS_SCRIPT="Allsubmit_analysis"
                 fi
                 shift
+                ;;
+            -t|--theoretical)
+                ZERO_FOLDER+=".theoretical"
+                shift
+                ;;
+            -r|--resources)
+                if [[ -z "$2" ]]; then
+                    echo "Error: --resources option requires an argument." >&2
+                    exit 1
+                fi
+                CASE_RESOURCES+="_$2"
+                shift 2
                 ;;
             -h|--help)
                 usage
@@ -168,6 +187,14 @@ validate_case_name() {
 prepare() {
     #--- create main case folder ---#
 
+    # reference folder with sanity check
+    local reference="${case_reference}/${CASE_RESOURCES}"
+
+    if [[ ! -d ${reference} ]]; then
+        echo "Error: Reference folder '${reference}' does not exist." >&2
+        exit 1
+    fi
+
     # make subdirectories
     local constant_folder="${case_folder}/constant"
     local system_folder="${case_folder}/system"
@@ -179,18 +206,18 @@ prepare() {
 
     # copy executable scripts to case folder
     cp "${BIN_DIR}/Util_functions" "${case_folder}/."
-    cp "${case_reference}/bin/"* "${case_folder}/."
+    cp "${reference}/bin/"* "${case_folder}/."
 
     # copy files from case reference to specific case folders
-    cp -r "${case_reference}/boundary_conditions/0.orig" "${case_folder}/."
+    cp -r "${reference}/boundary_conditions/${ZERO_FOLDER}" "${case_folder}/0.orig"
 
     # copy files from case reference to resources folder
-    cp -r "${case_reference}/dicts" "${resources_folder}/."
-    cp -r "${case_reference}/geometry" "${resources_folder}/."
-    cp -r "${case_reference}/properties" "${resources_folder}/."
-    cp -r "${case_reference}/function_objects" "${resources_folder}/."
-    cp -r "${case_reference}/data" "${resources_folder}/."
-    cp -r "${case_reference}/boundary_conditions/boundaryData" "${resources_folder}/data/."
+    cp -r "${reference}/dicts" "${resources_folder}/."
+    cp -r "${reference}/geometry" "${resources_folder}/."
+    cp -r "${reference}/properties" "${resources_folder}/."
+    cp -r "${reference}/function_objects" "${resources_folder}/."
+    cp -r "${reference}/data" "${resources_folder}/."
+    cp -r "${reference}/boundary_conditions/boundaryData" "${resources_folder}/data/."
 
     echo "+--- Created case folder"
 
diff --git a/resources/bin/Util_functions b/resources/bin/Util_functions
--- a/resources/bin/Util_functions
+++ b/resources/bin/Util_functions
@@ -136,7 +136,7 @@ set_parallel() {
 }
 
 ###############################################################################
-# set_fos <FOsDir>
+# set_fos <FOsDir> <path-to-file>
 #
 # • Adds all FOs in the directory to system/controlDict/functions.
 # • FOs are sorted by the number at the end of their filename.
@@ -150,6 +150,7 @@ set_parallel() {
 set_fos() {
     local fo_name_pattern="^FO_.*_([0-9]+\.?[0-9]*)$"
     local fo_dir="$1"
+    local functions_file="$2"
 
     #--- sanity checks ---#
     if [[ -z $fo_dir || ! -d $fo_dir ]]; then
@@ -157,10 +158,8 @@ set_fos() {
         return 1
     fi
 
-    local control_dict="system/controlDict"
-
-    if [[ ! -f $control_dict ]]; then
-        echo "Error: ${control_dict} not found in system folder" >&2
+    if [[ ! -f $functions_file ]]; then
+        echo "Error: ${functions_file} not found in system folder" >&2
         return 1
     fi
 
@@ -178,24 +177,29 @@ set_fos() {
     )
 
     # Build the block to insert
-    fo_block="functions {\n"
+    fo_block=""
     echo "Adding Function Objects:"
+
     for fo in "${sorted_fo_files[@]}"; do
         echo -e "\t⇲ $(basename "$fo")"
         fo_block+="\t#include \"./"$fo"\"\n"
     done
-    fo_block+="}\n"
+    
+    if [[ $(basename "${functions_file}") == "controlDict" ]]; then
+        fo_block="functions {\n${fo_block}}"
+        fo_block+="}\n"
+    fi
 
     # Insert the block before the last line of controlDict
     tmp_file=$(mktemp)
-    total_lines=$(wc -l < "$control_dict")
+    total_lines=$(wc -l < "$functions_file")
     insert_line=$((total_lines - 1))
-    head -n "$insert_line" "$control_dict" > "$tmp_file"
+    head -n "$insert_line" "$functions_file" > "$tmp_file"
     echo -e "$fo_block" >> "$tmp_file"
-    tail -n 1 "$control_dict" >> "$tmp_file"
+    tail -n 1 "$functions_file" >> "$tmp_file"
 
     # Overwrite original controlDict
-    mv "$tmp_file" "$control_dict"
+    mv "$tmp_file" "$functions_file"
 }
 
 ###############################################################################
@@ -351,7 +355,7 @@ set_lib() {
             return 0
         fi
         sed -E -i \
-            "s/^([[:space:]]*libs[[:space:]]*\([^)]*)\);/\1 $tok);/" "$file"
+            "s/^([[:space:]]*libs[[:space:]]*\([^)]*)\);/\1 \"$tok\");/" "$file"
         echo "Inserting '$tok' into inline libs(...)."
     fi
 
@@ -373,7 +377,7 @@ set_lib() {
         sed -E -i \
             "/^[[:space:]]*libs[[:space:]]*\($/,/^[[:space:]]*\);/{
                 /^[[:space:]]*\);/ i\\
-${indent}${tok}
+${indent}\"${tok}\"
             }" "$file"
         echo "Inserting '$tok' into multiline libs(...)."
         return 0
