fix: correct simulations related executables

diff --git a/resources/bin/Util_functions b/resources/bin/Util_functions
--- a/resources/bin/Util_functions
+++ b/resources/bin/Util_functions
@@ -38,12 +38,11 @@ set_acquisition_time() {
     mapfile -d '' -t fo_files < <(find "$fo_dir" -type f -print0)
 
     for fo in "${fo_files[@]}"; do
-        sed -Ei "
-            s/(^[[:space:]]*timeStart[[:space:]]+).*/\1${start_time};/;
-            s/(^[[:space:]]*timeEnd[[:space:]]+).*/\1${end_time};/
-        " "$fo"
-
         if [[ ! " ${protected[*]} " =~ " $(basename "$fo") " ]]; then
+            sed -Ei "
+                s/(^[[:space:]]*timeStart[[:space:]]+).*/\1${start_time};/;
+                s/(^[[:space:]]*timeEnd[[:space:]]+).*/\1${end_time};/
+            " "$fo"
             sed -Ei "
                 s/(^[[:space:]]*executeInterval[[:space:]]+).*/\1${acquisition_dt};/;
                 s/(^[[:space:]]*writeInterval[[:space:]]+).*/\1${acquisition_dt};/
@@ -197,6 +196,42 @@ set_fos() {
 
     # Overwrite original controlDict
     mv "$tmp_file" "$control_dict"
+}
+
+###############################################################################
+# set_fo_states <common-state> <path-to-function-object>
+#
+# • Updates 'enabled' flag for all functions defined within the given function
+#   object file.
+# • Uses foamDictionary
+#
+###############################################################################
+set_fo_states() {
+    local enabled="$1"
+    local function_object_file="$2"
+
+    if [[ -z "${enabled}" || -z "${function_object_file}" ]]; then
+        echo "Usage: set_fo_states <on|off|true|false|1|0> " \
+            "<path-to-function-object>" >&2
+        return 2
+    fi
+
+    if [[ ! -f "${function_object_file}" ]]; then
+        echo "Error: File '$function_object_file' not found"
+        return 1
+    fi
+
+    if ! command -v foamDictionary >/dev/null 2>&1; then
+        echo "Error: foamDictionary not found in PATH."
+        return 1
+    fi
+
+    for dictionary in $(foamDictionary -keywords "${function_object_file}"); do
+        foamDictionary -entry ${dictionary}/enabled \
+            -set "${enabled}" \
+            "${function_object_file}" > /dev/null 2>&1
+        echo "Disabling '${dictionary}' in '${function_object_file}'."
+    done
 }
 
 ###############################################################################
diff --git a/resources/case_studies/AIJ_A/bin/Allrun_case b/resources/case_studies/AIJ_A/bin/Allrun_case
--- a/resources/case_studies/AIJ_A/bin/Allrun_case
+++ b/resources/case_studies/AIJ_A/bin/Allrun_case
@@ -84,21 +84,38 @@ cp -r "${data_resources}/boundaryData" "${local_props}/." || {
 # Make changes in files
 
 protected_fos=(
+    "FO_Q_3.1"
     "FO_yPlus_4"
     "FO_sampleyPlus_5"
     "FO_residuals_6"
     "FO_fieldAverage_8"
+    "FO_isoSurfaces_15.1"
     "FO_setMaxCo_16"
     "FO_setRelaxationFactors_17"
     "FO_setOuterCorrectors_18"
 )
 
+refinement_fos=(
+    "FO_sasRefineIndicator_8.8"
+    "FO_cuttingPlanesRefinement_14.2"
+    "FO_cuttingPlanesRefinement_14.3"
+    "FO_refinementInfo_19"
+)
+
+local_functions="${local_dicts}/function_objects"
+
+set_fos "${local_functions}" || {
+    echo "Error setting function objects" >&2
+    exit 1
+}
+
 if [ "${refinement}" = true ]; then
     protected_fos+=(
-        "FO_sasRefineIndicator_8.8"
-        "FO_cuttingPlanesRefinement_14.2"
-        "FO_refinementInfo_19"
+        ${refinement_fos[0]}
+        ${refinement_fos[1]}
+        ${refinement_fos[3]}
     )
+
     set_lib "mydynamicFvMesh" "${local_dicts}/controlDict" || {
         echo "Error setting dynamic mesh library" >&2
         exit 1
@@ -111,12 +128,15 @@ if [ "${refinement}" = true ]; then
         echo "Error setting turbulence model" >&2
         exit 1
     }
+else
+    for fo in "${refinement_fos[@]}"; do
+        set_fo_states "off" "${local_functions}/${fo}" || {
+            echo "Error disabling function object $fo" >&2
+            exit 1
+        }
+    done
 fi
 
-set_fos "${local_dicts}/function_objects" || {
-    echo "Error setting function objects" >&2
-    exit 1
-}
 set_acquisition_time $delta_t $start_time $end_time "${protected_fos[@]}" || {
     echo "Error setting acquisition time" >&2
     exit 1
